<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * BlockRef is one nested statement block (if-body, else-
 * body, for-body, switch-case body, try / catch / finally
 * body). Each block carries both hash variants so within-
 * language and cross-language block-duplicate detection
 * consume the same data.
 *
 * Generated from protobuf message <code>revund.worker.v1.BlockRef</code>
 */
class BlockRef extends \Google\Protobuf\Internal\Message
{
    /**
     * Kind of the construct that owns this block:
     * "if" | "else" | "elseif" | "for" | "case" |
     * "try" | "catch" | "finally" | "rescue" | "block".
     *
     * Generated from protobuf field <code>string kind = 1;</code>
     */
    protected $kind = '';
    /**
     * Generated from protobuf field <code>int32 start_line = 2;</code>
     */
    protected $start_line = 0;
    /**
     * Generated from protobuf field <code>int32 end_line = 3;</code>
     */
    protected $end_line = 0;
    /**
     * language-specific
     *
     * Generated from protobuf field <code>string hash = 4;</code>
     */
    protected $hash = '';
    /**
     * language-neutral
     *
     * Generated from protobuf field <code>string canonical_hash = 5;</code>
     */
    protected $canonical_hash = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $kind
     *           Kind of the construct that owns this block:
     *           "if" | "else" | "elseif" | "for" | "case" |
     *           "try" | "catch" | "finally" | "rescue" | "block".
     *     @type int $start_line
     *     @type int $end_line
     *     @type string $hash
     *           language-specific
     *     @type string $canonical_hash
     *           language-neutral
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * Kind of the construct that owns this block:
     * "if" | "else" | "elseif" | "for" | "case" |
     * "try" | "catch" | "finally" | "rescue" | "block".
     *
     * Generated from protobuf field <code>string kind = 1;</code>
     * @return string
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Kind of the construct that owns this block:
     * "if" | "else" | "elseif" | "for" | "case" |
     * "try" | "catch" | "finally" | "rescue" | "block".
     *
     * Generated from protobuf field <code>string kind = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKind(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 start_line = 2;</code>
     * @return int
     */
    public function getStartLine()
    {
        return $this->start_line;
    }

    /**
     * Generated from protobuf field <code>int32 start_line = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStartLine(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->start_line = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 end_line = 3;</code>
     * @return int
     */
    public function getEndLine()
    {
        return $this->end_line;
    }

    /**
     * Generated from protobuf field <code>int32 end_line = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setEndLine(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->end_line = $var;

        return $this;
    }

    /**
     * language-specific
     *
     * Generated from protobuf field <code>string hash = 4;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * language-specific
     *
     * Generated from protobuf field <code>string hash = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setHash(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->hash = $var;

        return $this;
    }

    /**
     * language-neutral
     *
     * Generated from protobuf field <code>string canonical_hash = 5;</code>
     * @return string
     */
    public function getCanonicalHash()
    {
        return $this->canonical_hash;
    }

    /**
     * language-neutral
     *
     * Generated from protobuf field <code>string canonical_hash = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCanonicalHash(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->canonical_hash = $var;

        return $this;
    }

}

