<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ConcernEvidenceRef is one categorized signal the worker
 * extracted. The bot demuxes by category into the typed
 * ConcernSet on lang.FileView.
 * Canonical category values:
 *   "presentation"  — UI rendering / templates / JSX
 *   "state"         — in-memory state, hooks, signals
 *   "transport"     — server-side request handlers
 *   "network"       — outbound HTTP / RPC / message-broker
 *   "dataaccess"    — persistent storage operations
 *   "io"            — filesystem, OS-level IO
 *   "config"        — env reads, flags, dotenv
 *   "business"      — high-complexity decision logic
 * New categories can be added by workers; the bot
 * silently drops unknown values so older bots keep working.
 *
 * Generated from protobuf message <code>revund.worker.v1.ConcernEvidenceRef</code>
 */
class ConcernEvidenceRef extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string category = 1;</code>
     */
    protected $category = '';
    /**
     * Generated from protobuf field <code>int32 line = 2;</code>
     */
    protected $line = 0;
    /**
     * Generated from protobuf field <code>string symbol = 3;</code>
     */
    protected $symbol = '';
    /**
     * Generated from protobuf field <code>string note = 4;</code>
     */
    protected $note = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $category
     *     @type int $line
     *     @type string $symbol
     *     @type string $note
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string category = 1;</code>
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Generated from protobuf field <code>string category = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCategory(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->category = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 line = 2;</code>
     * @return int
     */
    public function getLine()
    {
        return $this->line;
    }

    /**
     * Generated from protobuf field <code>int32 line = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLine(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->line = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string symbol = 3;</code>
     * @return string
     */
    public function getSymbol()
    {
        return $this->symbol;
    }

    /**
     * Generated from protobuf field <code>string symbol = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSymbol(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->symbol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string note = 4;</code>
     * @return string
     */
    public function getNote()
    {
        return $this->note;
    }

    /**
     * Generated from protobuf field <code>string note = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setNote(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->note = $var;

        return $this;
    }

}

