<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * DeclRef is one top-level declaration. Kind is a lowercase
 * string from the canonical set: function | method | type |
 * interface | const | var | class | trait | enum | module |
 * constant | component | hook. Workers MAY advertise
 * kinds not in this list; the bot's structural detectors
 * switch on the canonical set and silently ignore unknowns
 * (forward-compat).
 *
 * Generated from protobuf message <code>revund.worker.v1.DeclRef</code>
 */
class DeclRef extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string kind = 2;</code>
     */
    protected $kind = '';
    /**
     * Generated from protobuf field <code>int32 line = 3;</code>
     */
    protected $line = 0;
    /**
     * Generated from protobuf field <code>int32 end_line = 4;</code>
     */
    protected $end_line = 0;
    /**
     * Exported is whether this declaration is visible
     * outside its compilation unit / module / namespace.
     * Languages without formal export concepts (PHP, Ruby)
     * set this to true for top-level decls.
     *
     * Generated from protobuf field <code>bool exported = 5;</code>
     */
    protected $exported = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $kind
     *     @type int $line
     *     @type int $end_line
     *     @type bool $exported
     *           Exported is whether this declaration is visible
     *           outside its compilation unit / module / namespace.
     *           Languages without formal export concepts (PHP, Ruby)
     *           set this to true for top-level decls.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string kind = 2;</code>
     * @return string
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     * Generated from protobuf field <code>string kind = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKind(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 line = 3;</code>
     * @return int
     */
    public function getLine()
    {
        return $this->line;
    }

    /**
     * Generated from protobuf field <code>int32 line = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLine(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->line = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 end_line = 4;</code>
     * @return int
     */
    public function getEndLine()
    {
        return $this->end_line;
    }

    /**
     * Generated from protobuf field <code>int32 end_line = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setEndLine(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->end_line = $var;

        return $this;
    }

    /**
     * Exported is whether this declaration is visible
     * outside its compilation unit / module / namespace.
     * Languages without formal export concepts (PHP, Ruby)
     * set this to true for top-level decls.
     *
     * Generated from protobuf field <code>bool exported = 5;</code>
     * @return bool
     */
    public function getExported()
    {
        return $this->exported;
    }

    /**
     * Exported is whether this declaration is visible
     * outside its compilation unit / module / namespace.
     * Languages without formal export concepts (PHP, Ruby)
     * set this to true for top-level decls.
     *
     * Generated from protobuf field <code>bool exported = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setExported(bool $var)
    {
        $this->exported = $var;

        return $this;
    }

}

