<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>revund.worker.v1.DescribeResponse</code>
 */
class DescribeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Name is a human-readable identifier for this worker,
     * e.g. "ts-worker", "php-worker", "ruby-worker", or a
     * community-chosen name like "my-fancy-go-worker".
     * Used for logging and observability; NOT used for
     * routing (languages field does that).
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Version is the worker's semantic version. Logged at
     * startup and surfaced in debug bundles so we can tie
     * findings to a specific worker build.
     *
     * Generated from protobuf field <code>string version = 2;</code>
     */
    protected $version = '';
    /**
     * Languages the worker can parse. Lowercase canonical
     * names matching the lang.Language enum on the Go side:
     * "typescript", "javascript", "go", "php", "ruby",
     * "python", "rust", "java", "kotlin", "swift", "csharp".
     * A worker MAY advertise multiple languages (a tree-
     * sitter-based worker might handle ten). The bot routes
     * each language's files to the worker that advertises
     * it; on conflict (multiple workers advertise the same
     * language), the bot picks the first one registered.
     *
     * Generated from protobuf field <code>repeated string languages = 3;</code>
     */
    private $languages;
    /**
     * Capabilities is the set of optional features this
     * worker implements beyond the required Parse RPC.
     * Known values:
     *   "parse"            — Parse RPC (REQUIRED; always
     *                        present in a healthy worker)
     *   "resolve_symbols"  — symbol-decl resolution; the
     *                        worker can return declarations
     *                        of identifiers referenced in
     *                        changed code.
     *   "diagnostics"      — language-specific type-check
     *                        diagnostics (tsc, PHPStan,
     *                        Sorbet, etc.).
     *   "self_fetch"       — worker can clone the repo
     *                        itself given a RepoSource
     *                        (url + ref + auth_token) on
     *                        the request. Required for
     *                        cross-host deployments where
     *                        the bot and worker do NOT
     *                        share a filesystem. When this
     *                        capability is advertised, the
     *                        bot sends `repo_source`
     *                        instead of `repo_path` on
     *                        Parse / ResolveSymbols /
     *                        RunDiagnostics RPCs.
     * New capabilities can be added without breaking older
     * bots — they advertise but the bot ignores capabilities
     * it doesn't recognize.
     *
     * Generated from protobuf field <code>repeated string capabilities = 4;</code>
     */
    private $capabilities;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Name is a human-readable identifier for this worker,
     *           e.g. "ts-worker", "php-worker", "ruby-worker", or a
     *           community-chosen name like "my-fancy-go-worker".
     *           Used for logging and observability; NOT used for
     *           routing (languages field does that).
     *     @type string $version
     *           Version is the worker's semantic version. Logged at
     *           startup and surfaced in debug bundles so we can tie
     *           findings to a specific worker build.
     *     @type string[] $languages
     *           Languages the worker can parse. Lowercase canonical
     *           names matching the lang.Language enum on the Go side:
     *           "typescript", "javascript", "go", "php", "ruby",
     *           "python", "rust", "java", "kotlin", "swift", "csharp".
     *           A worker MAY advertise multiple languages (a tree-
     *           sitter-based worker might handle ten). The bot routes
     *           each language's files to the worker that advertises
     *           it; on conflict (multiple workers advertise the same
     *           language), the bot picks the first one registered.
     *     @type string[] $capabilities
     *           Capabilities is the set of optional features this
     *           worker implements beyond the required Parse RPC.
     *           Known values:
     *             "parse"            — Parse RPC (REQUIRED; always
     *                                  present in a healthy worker)
     *             "resolve_symbols"  — symbol-decl resolution; the
     *                                  worker can return declarations
     *                                  of identifiers referenced in
     *                                  changed code.
     *             "diagnostics"      — language-specific type-check
     *                                  diagnostics (tsc, PHPStan,
     *                                  Sorbet, etc.).
     *             "self_fetch"       — worker can clone the repo
     *                                  itself given a RepoSource
     *                                  (url + ref + auth_token) on
     *                                  the request. Required for
     *                                  cross-host deployments where
     *                                  the bot and worker do NOT
     *                                  share a filesystem. When this
     *                                  capability is advertised, the
     *                                  bot sends `repo_source`
     *                                  instead of `repo_path` on
     *                                  Parse / ResolveSymbols /
     *                                  RunDiagnostics RPCs.
     *           New capabilities can be added without breaking older
     *           bots — they advertise but the bot ignores capabilities
     *           it doesn't recognize.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * Name is a human-readable identifier for this worker,
     * e.g. "ts-worker", "php-worker", "ruby-worker", or a
     * community-chosen name like "my-fancy-go-worker".
     * Used for logging and observability; NOT used for
     * routing (languages field does that).
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Name is a human-readable identifier for this worker,
     * e.g. "ts-worker", "php-worker", "ruby-worker", or a
     * community-chosen name like "my-fancy-go-worker".
     * Used for logging and observability; NOT used for
     * routing (languages field does that).
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Version is the worker's semantic version. Logged at
     * startup and surfaced in debug bundles so we can tie
     * findings to a specific worker build.
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Version is the worker's semantic version. Logged at
     * startup and surfaced in debug bundles so we can tie
     * findings to a specific worker build.
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->version = $var;

        return $this;
    }

    /**
     * Languages the worker can parse. Lowercase canonical
     * names matching the lang.Language enum on the Go side:
     * "typescript", "javascript", "go", "php", "ruby",
     * "python", "rust", "java", "kotlin", "swift", "csharp".
     * A worker MAY advertise multiple languages (a tree-
     * sitter-based worker might handle ten). The bot routes
     * each language's files to the worker that advertises
     * it; on conflict (multiple workers advertise the same
     * language), the bot picks the first one registered.
     *
     * Generated from protobuf field <code>repeated string languages = 3;</code>
     * @return RepeatedField<string>
     */
    public function getLanguages()
    {
        return $this->languages;
    }

    /**
     * Languages the worker can parse. Lowercase canonical
     * names matching the lang.Language enum on the Go side:
     * "typescript", "javascript", "go", "php", "ruby",
     * "python", "rust", "java", "kotlin", "swift", "csharp".
     * A worker MAY advertise multiple languages (a tree-
     * sitter-based worker might handle ten). The bot routes
     * each language's files to the worker that advertises
     * it; on conflict (multiple workers advertise the same
     * language), the bot picks the first one registered.
     *
     * Generated from protobuf field <code>repeated string languages = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setLanguages(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->languages = $arr;

        return $this;
    }

    /**
     * Capabilities is the set of optional features this
     * worker implements beyond the required Parse RPC.
     * Known values:
     *   "parse"            — Parse RPC (REQUIRED; always
     *                        present in a healthy worker)
     *   "resolve_symbols"  — symbol-decl resolution; the
     *                        worker can return declarations
     *                        of identifiers referenced in
     *                        changed code.
     *   "diagnostics"      — language-specific type-check
     *                        diagnostics (tsc, PHPStan,
     *                        Sorbet, etc.).
     *   "self_fetch"       — worker can clone the repo
     *                        itself given a RepoSource
     *                        (url + ref + auth_token) on
     *                        the request. Required for
     *                        cross-host deployments where
     *                        the bot and worker do NOT
     *                        share a filesystem. When this
     *                        capability is advertised, the
     *                        bot sends `repo_source`
     *                        instead of `repo_path` on
     *                        Parse / ResolveSymbols /
     *                        RunDiagnostics RPCs.
     * New capabilities can be added without breaking older
     * bots — they advertise but the bot ignores capabilities
     * it doesn't recognize.
     *
     * Generated from protobuf field <code>repeated string capabilities = 4;</code>
     * @return RepeatedField<string>
     */
    public function getCapabilities()
    {
        return $this->capabilities;
    }

    /**
     * Capabilities is the set of optional features this
     * worker implements beyond the required Parse RPC.
     * Known values:
     *   "parse"            — Parse RPC (REQUIRED; always
     *                        present in a healthy worker)
     *   "resolve_symbols"  — symbol-decl resolution; the
     *                        worker can return declarations
     *                        of identifiers referenced in
     *                        changed code.
     *   "diagnostics"      — language-specific type-check
     *                        diagnostics (tsc, PHPStan,
     *                        Sorbet, etc.).
     *   "self_fetch"       — worker can clone the repo
     *                        itself given a RepoSource
     *                        (url + ref + auth_token) on
     *                        the request. Required for
     *                        cross-host deployments where
     *                        the bot and worker do NOT
     *                        share a filesystem. When this
     *                        capability is advertised, the
     *                        bot sends `repo_source`
     *                        instead of `repo_path` on
     *                        Parse / ResolveSymbols /
     *                        RunDiagnostics RPCs.
     * New capabilities can be added without breaking older
     * bots — they advertise but the bot ignores capabilities
     * it doesn't recognize.
     *
     * Generated from protobuf field <code>repeated string capabilities = 4;</code>
     * @param string[] $var
     * @return $this
     */
    public function setCapabilities(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->capabilities = $arr;

        return $this;
    }

}

