<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>revund.worker.v1.DiagnosticsResponse</code>
 */
class DiagnosticsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.Diagnostic diagnostics = 1;</code>
     */
    private $diagnostics;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Revund\Worker\V1\Diagnostic[] $diagnostics
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.Diagnostic diagnostics = 1;</code>
     * @return RepeatedField<\Revund\Worker\V1\Diagnostic>
     */
    public function getDiagnostics()
    {
        return $this->diagnostics;
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.Diagnostic diagnostics = 1;</code>
     * @param \Revund\Worker\V1\Diagnostic[] $var
     * @return $this
     */
    public function setDiagnostics(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Revund\Worker\V1\Diagnostic::class);
        $this->diagnostics = $arr;

        return $this;
    }

}

