<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>revund.worker.v1.Diagnostic</code>
 */
class Diagnostic extends \Google\Protobuf\Internal\Message
{
    /**
     * repo-relative
     *
     * Generated from protobuf field <code>string file = 1;</code>
     */
    protected $file = '';
    /**
     * Generated from protobuf field <code>int32 line = 2;</code>
     */
    protected $line = 0;
    /**
     * Generated from protobuf field <code>int32 col = 3;</code>
     */
    protected $col = 0;
    /**
     * e.g. "TS2345", "PHPStan.Error", "Sorbet:7008"
     *
     * Generated from protobuf field <code>string code = 4;</code>
     */
    protected $code = '';
    /**
     * Generated from protobuf field <code>string message = 5;</code>
     */
    protected $message = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $file
     *           repo-relative
     *     @type int $line
     *     @type int $col
     *     @type string $code
     *           e.g. "TS2345", "PHPStan.Error", "Sorbet:7008"
     *     @type string $message
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * repo-relative
     *
     * Generated from protobuf field <code>string file = 1;</code>
     * @return string
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * repo-relative
     *
     * Generated from protobuf field <code>string file = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFile(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->file = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 line = 2;</code>
     * @return int
     */
    public function getLine()
    {
        return $this->line;
    }

    /**
     * Generated from protobuf field <code>int32 line = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setLine(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->line = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 col = 3;</code>
     * @return int
     */
    public function getCol()
    {
        return $this->col;
    }

    /**
     * Generated from protobuf field <code>int32 col = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCol(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->col = $var;

        return $this;
    }

    /**
     * e.g. "TS2345", "PHPStan.Error", "Sorbet:7008"
     *
     * Generated from protobuf field <code>string code = 4;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * e.g. "TS2345", "PHPStan.Error", "Sorbet:7008"
     *
     * Generated from protobuf field <code>string code = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setCode(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 5;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->message = $var;

        return $this;
    }

}

