<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>revund.worker.v1.DiagnosticsRequest</code>
 */
class DiagnosticsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * See ParseRequest.repo_path for the repo_path /
     * repo_source contract.
     *
     * Generated from protobuf field <code>string repo_path = 1;</code>
     */
    protected $repo_path = '';
    /**
     * Only return diagnostics whose file is in this set.
     * Empty = no filter (return everything tsc / PHPStan /
     * Sorbet found).
     *
     * Generated from protobuf field <code>repeated string filter_files = 2;</code>
     */
    private $filter_files;
    /**
     * Self-fetch source — set when the worker should clone
     * the repo itself instead of reading from repo_path.
     *
     * Generated from protobuf field <code>.revund.worker.v1.RepoSource repo_source = 3;</code>
     */
    protected $repo_source = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $repo_path
     *           See ParseRequest.repo_path for the repo_path /
     *           repo_source contract.
     *     @type string[] $filter_files
     *           Only return diagnostics whose file is in this set.
     *           Empty = no filter (return everything tsc / PHPStan /
     *           Sorbet found).
     *     @type \Revund\Worker\V1\RepoSource $repo_source
     *           Self-fetch source — set when the worker should clone
     *           the repo itself instead of reading from repo_path.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * See ParseRequest.repo_path for the repo_path /
     * repo_source contract.
     *
     * Generated from protobuf field <code>string repo_path = 1;</code>
     * @return string
     */
    public function getRepoPath()
    {
        return $this->repo_path;
    }

    /**
     * See ParseRequest.repo_path for the repo_path /
     * repo_source contract.
     *
     * Generated from protobuf field <code>string repo_path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRepoPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->repo_path = $var;

        return $this;
    }

    /**
     * Only return diagnostics whose file is in this set.
     * Empty = no filter (return everything tsc / PHPStan /
     * Sorbet found).
     *
     * Generated from protobuf field <code>repeated string filter_files = 2;</code>
     * @return RepeatedField<string>
     */
    public function getFilterFiles()
    {
        return $this->filter_files;
    }

    /**
     * Only return diagnostics whose file is in this set.
     * Empty = no filter (return everything tsc / PHPStan /
     * Sorbet found).
     *
     * Generated from protobuf field <code>repeated string filter_files = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setFilterFiles(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->filter_files = $arr;

        return $this;
    }

    /**
     * Self-fetch source — set when the worker should clone
     * the repo itself instead of reading from repo_path.
     *
     * Generated from protobuf field <code>.revund.worker.v1.RepoSource repo_source = 3;</code>
     * @return \Revund\Worker\V1\RepoSource|null
     */
    public function getRepoSource()
    {
        return $this->repo_source;
    }

    public function hasRepoSource()
    {
        return isset($this->repo_source);
    }

    public function clearRepoSource()
    {
        unset($this->repo_source);
    }

    /**
     * Self-fetch source — set when the worker should clone
     * the repo itself instead of reading from repo_path.
     *
     * Generated from protobuf field <code>.revund.worker.v1.RepoSource repo_source = 3;</code>
     * @param \Revund\Worker\V1\RepoSource $var
     * @return $this
     */
    public function setRepoSource(\Revund\Worker\V1\RepoSource|null $var)
    {
        $this->repo_source = $var;

        return $this;
    }

}

