<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * FunctionRef describes one function / method definition.
 * Carries the data the structural detectors need for
 * god-function, complexity, and the three DRY variants.
 *
 * Generated from protobuf message <code>revund.worker.v1.FunctionRef</code>
 */
class FunctionRef extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int32 start_line = 2;</code>
     */
    protected $start_line = 0;
    /**
     * Generated from protobuf field <code>int32 end_line = 3;</code>
     */
    protected $end_line = 0;
    /**
     * Cyclomatic complexity estimate (McCabe — count of
     * decision points + 1). Workers may compute it however
     * they prefer; the bot uses the value as a coarse
     * signal, not a precise measurement.
     *
     * Generated from protobuf field <code>int32 complexity = 4;</code>
     */
    protected $complexity = 0;
    /**
     * Generated from protobuf field <code>bool is_method = 5;</code>
     */
    protected $is_method = false;
    /**
     * Generated from protobuf field <code>bool is_exported = 6;</code>
     */
    protected $is_exported = false;
    /**
     * Hash is the LANGUAGE-SPECIFIC fingerprint of the
     * function body's AST shape. Two functions in the same
     * language with the same hash share structure modulo
     * identifier names + literal values. Empty when the
     * body was too small to be a meaningful DRY signal.
     * The hashing scheme is per-worker. Recommended: SHA-1
     * of a token stream, truncated to 16 hex chars. The
     * ts-worker reference implementation in
     * workers/ts/src/parser.ts is the template for new
     * workers.
     *
     * Generated from protobuf field <code>string hash = 7;</code>
     */
    protected $hash = '';
    /**
     * CanonicalHash is the LANGUAGE-NEUTRAL fingerprint
     * produced by mapping the function body's AST onto a
     * shared canonical token vocabulary. Two functions in
     * DIFFERENT languages with the same canonical hash share
     * a structural shape — the basis for cross-language
     * duplicate detection.
     * The canonical vocabulary is defined in
     * core/pkg/structural/lang/canonical.go. New workers
     * mirror that vocabulary; PR-able if a new construct
     * needs adding.
     *
     * Generated from protobuf field <code>string canonical_hash = 8;</code>
     */
    protected $canonical_hash = '';
    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.BlockRef blocks = 9;</code>
     */
    private $blocks;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int $start_line
     *     @type int $end_line
     *     @type int $complexity
     *           Cyclomatic complexity estimate (McCabe — count of
     *           decision points + 1). Workers may compute it however
     *           they prefer; the bot uses the value as a coarse
     *           signal, not a precise measurement.
     *     @type bool $is_method
     *     @type bool $is_exported
     *     @type string $hash
     *           Hash is the LANGUAGE-SPECIFIC fingerprint of the
     *           function body's AST shape. Two functions in the same
     *           language with the same hash share structure modulo
     *           identifier names + literal values. Empty when the
     *           body was too small to be a meaningful DRY signal.
     *           The hashing scheme is per-worker. Recommended: SHA-1
     *           of a token stream, truncated to 16 hex chars. The
     *           ts-worker reference implementation in
     *           workers/ts/src/parser.ts is the template for new
     *           workers.
     *     @type string $canonical_hash
     *           CanonicalHash is the LANGUAGE-NEUTRAL fingerprint
     *           produced by mapping the function body's AST onto a
     *           shared canonical token vocabulary. Two functions in
     *           DIFFERENT languages with the same canonical hash share
     *           a structural shape — the basis for cross-language
     *           duplicate detection.
     *           The canonical vocabulary is defined in
     *           core/pkg/structural/lang/canonical.go. New workers
     *           mirror that vocabulary; PR-able if a new construct
     *           needs adding.
     *     @type \Revund\Worker\V1\BlockRef[] $blocks
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 start_line = 2;</code>
     * @return int
     */
    public function getStartLine()
    {
        return $this->start_line;
    }

    /**
     * Generated from protobuf field <code>int32 start_line = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStartLine(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->start_line = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 end_line = 3;</code>
     * @return int
     */
    public function getEndLine()
    {
        return $this->end_line;
    }

    /**
     * Generated from protobuf field <code>int32 end_line = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setEndLine(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->end_line = $var;

        return $this;
    }

    /**
     * Cyclomatic complexity estimate (McCabe — count of
     * decision points + 1). Workers may compute it however
     * they prefer; the bot uses the value as a coarse
     * signal, not a precise measurement.
     *
     * Generated from protobuf field <code>int32 complexity = 4;</code>
     * @return int
     */
    public function getComplexity()
    {
        return $this->complexity;
    }

    /**
     * Cyclomatic complexity estimate (McCabe — count of
     * decision points + 1). Workers may compute it however
     * they prefer; the bot uses the value as a coarse
     * signal, not a precise measurement.
     *
     * Generated from protobuf field <code>int32 complexity = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setComplexity(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->complexity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_method = 5;</code>
     * @return bool
     */
    public function getIsMethod()
    {
        return $this->is_method;
    }

    /**
     * Generated from protobuf field <code>bool is_method = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsMethod(bool $var)
    {
        $this->is_method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool is_exported = 6;</code>
     * @return bool
     */
    public function getIsExported()
    {
        return $this->is_exported;
    }

    /**
     * Generated from protobuf field <code>bool is_exported = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsExported(bool $var)
    {
        $this->is_exported = $var;

        return $this;
    }

    /**
     * Hash is the LANGUAGE-SPECIFIC fingerprint of the
     * function body's AST shape. Two functions in the same
     * language with the same hash share structure modulo
     * identifier names + literal values. Empty when the
     * body was too small to be a meaningful DRY signal.
     * The hashing scheme is per-worker. Recommended: SHA-1
     * of a token stream, truncated to 16 hex chars. The
     * ts-worker reference implementation in
     * workers/ts/src/parser.ts is the template for new
     * workers.
     *
     * Generated from protobuf field <code>string hash = 7;</code>
     * @return string
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * Hash is the LANGUAGE-SPECIFIC fingerprint of the
     * function body's AST shape. Two functions in the same
     * language with the same hash share structure modulo
     * identifier names + literal values. Empty when the
     * body was too small to be a meaningful DRY signal.
     * The hashing scheme is per-worker. Recommended: SHA-1
     * of a token stream, truncated to 16 hex chars. The
     * ts-worker reference implementation in
     * workers/ts/src/parser.ts is the template for new
     * workers.
     *
     * Generated from protobuf field <code>string hash = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setHash(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->hash = $var;

        return $this;
    }

    /**
     * CanonicalHash is the LANGUAGE-NEUTRAL fingerprint
     * produced by mapping the function body's AST onto a
     * shared canonical token vocabulary. Two functions in
     * DIFFERENT languages with the same canonical hash share
     * a structural shape — the basis for cross-language
     * duplicate detection.
     * The canonical vocabulary is defined in
     * core/pkg/structural/lang/canonical.go. New workers
     * mirror that vocabulary; PR-able if a new construct
     * needs adding.
     *
     * Generated from protobuf field <code>string canonical_hash = 8;</code>
     * @return string
     */
    public function getCanonicalHash()
    {
        return $this->canonical_hash;
    }

    /**
     * CanonicalHash is the LANGUAGE-NEUTRAL fingerprint
     * produced by mapping the function body's AST onto a
     * shared canonical token vocabulary. Two functions in
     * DIFFERENT languages with the same canonical hash share
     * a structural shape — the basis for cross-language
     * duplicate detection.
     * The canonical vocabulary is defined in
     * core/pkg/structural/lang/canonical.go. New workers
     * mirror that vocabulary; PR-able if a new construct
     * needs adding.
     *
     * Generated from protobuf field <code>string canonical_hash = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCanonicalHash(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->canonical_hash = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.BlockRef blocks = 9;</code>
     * @return RepeatedField<\Revund\Worker\V1\BlockRef>
     */
    public function getBlocks()
    {
        return $this->blocks;
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.BlockRef blocks = 9;</code>
     * @param \Revund\Worker\V1\BlockRef[] $var
     * @return $this
     */
    public function setBlocks(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Revund\Worker\V1\BlockRef::class);
        $this->blocks = $arr;

        return $this;
    }

}

