<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ImportRef is one import / require / use declaration.
 *
 * Generated from protobuf message <code>revund.worker.v1.ImportRef</code>
 */
class ImportRef extends \Google\Protobuf\Internal\Message
{
    /**
     * Raw module identifier as written in source. The bot
     * does NOT resolve this against the language's module
     * system; that's the worker's job if it advertises
     * resolve_symbols.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * Local binding when the language allows renaming on
     * import (Go: `import f "fmt"`, JS: `import { x as y }`,
     * PHP: `use Foo\Bar as B`, Ruby: autoload). Empty when
     * not applicable or not aliased.
     *
     * Generated from protobuf field <code>string alias = 2;</code>
     */
    protected $alias = '';
    /**
     * 1-based line number in the source file.
     *
     * Generated from protobuf field <code>int32 line = 3;</code>
     */
    protected $line = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *           Raw module identifier as written in source. The bot
     *           does NOT resolve this against the language's module
     *           system; that's the worker's job if it advertises
     *           resolve_symbols.
     *     @type string $alias
     *           Local binding when the language allows renaming on
     *           import (Go: `import f "fmt"`, JS: `import { x as y }`,
     *           PHP: `use Foo\Bar as B`, Ruby: autoload). Empty when
     *           not applicable or not aliased.
     *     @type int $line
     *           1-based line number in the source file.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * Raw module identifier as written in source. The bot
     * does NOT resolve this against the language's module
     * system; that's the worker's job if it advertises
     * resolve_symbols.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Raw module identifier as written in source. The bot
     * does NOT resolve this against the language's module
     * system; that's the worker's job if it advertises
     * resolve_symbols.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

    /**
     * Local binding when the language allows renaming on
     * import (Go: `import f "fmt"`, JS: `import { x as y }`,
     * PHP: `use Foo\Bar as B`, Ruby: autoload). Empty when
     * not applicable or not aliased.
     *
     * Generated from protobuf field <code>string alias = 2;</code>
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * Local binding when the language allows renaming on
     * import (Go: `import f "fmt"`, JS: `import { x as y }`,
     * PHP: `use Foo\Bar as B`, Ruby: autoload). Empty when
     * not applicable or not aliased.
     *
     * Generated from protobuf field <code>string alias = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAlias(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->alias = $var;

        return $this;
    }

    /**
     * 1-based line number in the source file.
     *
     * Generated from protobuf field <code>int32 line = 3;</code>
     * @return int
     */
    public function getLine()
    {
        return $this->line;
    }

    /**
     * 1-based line number in the source file.
     *
     * Generated from protobuf field <code>int32 line = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLine(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->line = $var;

        return $this;
    }

}

