<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * ParsedFile carries the minimal AST surface every
 * structural detector consumes. Shape is universal across
 * languages — implementations populate the fields their
 * language meaningfully exposes and leave the rest empty.
 *
 * Generated from protobuf message <code>revund.worker.v1.ParsedFile</code>
 */
class ParsedFile extends \Google\Protobuf\Internal\Message
{
    /**
     * Repo-relative path, slash-normalized. Echoed back from
     * the request so the bot can correlate response files
     * with request files without ordering assumptions.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * The language tag the worker assigned to this file.
     * Usually matches one of the languages from the worker's
     * Describe response. Set even on parse errors.
     *
     * Generated from protobuf field <code>string language = 2;</code>
     */
    protected $language = '';
    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.ImportRef imports = 3;</code>
     */
    private $imports;
    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.DeclRef decls = 4;</code>
     */
    private $decls;
    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.FunctionRef functions = 5;</code>
     */
    private $functions;
    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.ConcernEvidenceRef concerns = 7;</code>
     */
    private $concerns;
    /**
     * Non-empty when the worker failed to parse this file
     * cleanly. The other fields may still carry partial
     * results — workers should return whatever the parser
     * salvaged so detectors get USEFUL signal even on
     * syntactically-broken files.
     *
     * Generated from protobuf field <code>string parse_error = 6;</code>
     */
    protected $parse_error = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *           Repo-relative path, slash-normalized. Echoed back from
     *           the request so the bot can correlate response files
     *           with request files without ordering assumptions.
     *     @type string $language
     *           The language tag the worker assigned to this file.
     *           Usually matches one of the languages from the worker's
     *           Describe response. Set even on parse errors.
     *     @type \Revund\Worker\V1\ImportRef[] $imports
     *     @type \Revund\Worker\V1\DeclRef[] $decls
     *     @type \Revund\Worker\V1\FunctionRef[] $functions
     *     @type \Revund\Worker\V1\ConcernEvidenceRef[] $concerns
     *     @type string $parse_error
     *           Non-empty when the worker failed to parse this file
     *           cleanly. The other fields may still carry partial
     *           results — workers should return whatever the parser
     *           salvaged so detectors get USEFUL signal even on
     *           syntactically-broken files.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * Repo-relative path, slash-normalized. Echoed back from
     * the request so the bot can correlate response files
     * with request files without ordering assumptions.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Repo-relative path, slash-normalized. Echoed back from
     * the request so the bot can correlate response files
     * with request files without ordering assumptions.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->path = $var;

        return $this;
    }

    /**
     * The language tag the worker assigned to this file.
     * Usually matches one of the languages from the worker's
     * Describe response. Set even on parse errors.
     *
     * Generated from protobuf field <code>string language = 2;</code>
     * @return string
     */
    public function getLanguage()
    {
        return $this->language;
    }

    /**
     * The language tag the worker assigned to this file.
     * Usually matches one of the languages from the worker's
     * Describe response. Set even on parse errors.
     *
     * Generated from protobuf field <code>string language = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLanguage(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->language = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.ImportRef imports = 3;</code>
     * @return RepeatedField<\Revund\Worker\V1\ImportRef>
     */
    public function getImports()
    {
        return $this->imports;
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.ImportRef imports = 3;</code>
     * @param \Revund\Worker\V1\ImportRef[] $var
     * @return $this
     */
    public function setImports(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Revund\Worker\V1\ImportRef::class);
        $this->imports = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.DeclRef decls = 4;</code>
     * @return RepeatedField<\Revund\Worker\V1\DeclRef>
     */
    public function getDecls()
    {
        return $this->decls;
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.DeclRef decls = 4;</code>
     * @param \Revund\Worker\V1\DeclRef[] $var
     * @return $this
     */
    public function setDecls(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Revund\Worker\V1\DeclRef::class);
        $this->decls = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.FunctionRef functions = 5;</code>
     * @return RepeatedField<\Revund\Worker\V1\FunctionRef>
     */
    public function getFunctions()
    {
        return $this->functions;
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.FunctionRef functions = 5;</code>
     * @param \Revund\Worker\V1\FunctionRef[] $var
     * @return $this
     */
    public function setFunctions(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Revund\Worker\V1\FunctionRef::class);
        $this->functions = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.ConcernEvidenceRef concerns = 7;</code>
     * @return RepeatedField<\Revund\Worker\V1\ConcernEvidenceRef>
     */
    public function getConcerns()
    {
        return $this->concerns;
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.ConcernEvidenceRef concerns = 7;</code>
     * @param \Revund\Worker\V1\ConcernEvidenceRef[] $var
     * @return $this
     */
    public function setConcerns(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Revund\Worker\V1\ConcernEvidenceRef::class);
        $this->concerns = $arr;

        return $this;
    }

    /**
     * Non-empty when the worker failed to parse this file
     * cleanly. The other fields may still carry partial
     * results — workers should return whatever the parser
     * salvaged so detectors get USEFUL signal even on
     * syntactically-broken files.
     *
     * Generated from protobuf field <code>string parse_error = 6;</code>
     * @return string
     */
    public function getParseError()
    {
        return $this->parse_error;
    }

    /**
     * Non-empty when the worker failed to parse this file
     * cleanly. The other fields may still carry partial
     * results — workers should return whatever the parser
     * salvaged so detectors get USEFUL signal even on
     * syntactically-broken files.
     *
     * Generated from protobuf field <code>string parse_error = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setParseError(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->parse_error = $var;

        return $this;
    }

}

