<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>revund.worker.v1.ParseRequest</code>
 */
class ParseRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Absolute path to the repo root. The worker resolves
     * file paths relative to this root.
     * Exactly one of repo_path / repo_source is populated
     * per request. repo_path is set when the bot and
     * worker share a filesystem (CLI / local sidecar /
     * pod-with-shared-volume). repo_source is set when
     * the worker advertises "self_fetch" and the bot is
     * dialing across the network.
     *
     * Generated from protobuf field <code>string repo_path = 1;</code>
     */
    protected $repo_path = '';
    /**
     * Repo-relative paths to parse. Slash-normalized,
     * forward-slash separator regardless of platform.
     *
     * Generated from protobuf field <code>repeated string files = 2;</code>
     */
    private $files;
    /**
     * Self-fetch source — populated when the bot wants
     * the worker to clone the repo itself. See RepoSource
     * for the capability gate and security expectations.
     *
     * Generated from protobuf field <code>.revund.worker.v1.RepoSource repo_source = 3;</code>
     */
    protected $repo_source = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $repo_path
     *           Absolute path to the repo root. The worker resolves
     *           file paths relative to this root.
     *           Exactly one of repo_path / repo_source is populated
     *           per request. repo_path is set when the bot and
     *           worker share a filesystem (CLI / local sidecar /
     *           pod-with-shared-volume). repo_source is set when
     *           the worker advertises "self_fetch" and the bot is
     *           dialing across the network.
     *     @type string[] $files
     *           Repo-relative paths to parse. Slash-normalized,
     *           forward-slash separator regardless of platform.
     *     @type \Revund\Worker\V1\RepoSource $repo_source
     *           Self-fetch source — populated when the bot wants
     *           the worker to clone the repo itself. See RepoSource
     *           for the capability gate and security expectations.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * Absolute path to the repo root. The worker resolves
     * file paths relative to this root.
     * Exactly one of repo_path / repo_source is populated
     * per request. repo_path is set when the bot and
     * worker share a filesystem (CLI / local sidecar /
     * pod-with-shared-volume). repo_source is set when
     * the worker advertises "self_fetch" and the bot is
     * dialing across the network.
     *
     * Generated from protobuf field <code>string repo_path = 1;</code>
     * @return string
     */
    public function getRepoPath()
    {
        return $this->repo_path;
    }

    /**
     * Absolute path to the repo root. The worker resolves
     * file paths relative to this root.
     * Exactly one of repo_path / repo_source is populated
     * per request. repo_path is set when the bot and
     * worker share a filesystem (CLI / local sidecar /
     * pod-with-shared-volume). repo_source is set when
     * the worker advertises "self_fetch" and the bot is
     * dialing across the network.
     *
     * Generated from protobuf field <code>string repo_path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRepoPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->repo_path = $var;

        return $this;
    }

    /**
     * Repo-relative paths to parse. Slash-normalized,
     * forward-slash separator regardless of platform.
     *
     * Generated from protobuf field <code>repeated string files = 2;</code>
     * @return RepeatedField<string>
     */
    public function getFiles()
    {
        return $this->files;
    }

    /**
     * Repo-relative paths to parse. Slash-normalized,
     * forward-slash separator regardless of platform.
     *
     * Generated from protobuf field <code>repeated string files = 2;</code>
     * @param string[] $var
     * @return $this
     */
    public function setFiles(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->files = $arr;

        return $this;
    }

    /**
     * Self-fetch source — populated when the bot wants
     * the worker to clone the repo itself. See RepoSource
     * for the capability gate and security expectations.
     *
     * Generated from protobuf field <code>.revund.worker.v1.RepoSource repo_source = 3;</code>
     * @return \Revund\Worker\V1\RepoSource|null
     */
    public function getRepoSource()
    {
        return $this->repo_source;
    }

    public function hasRepoSource()
    {
        return isset($this->repo_source);
    }

    public function clearRepoSource()
    {
        unset($this->repo_source);
    }

    /**
     * Self-fetch source — populated when the bot wants
     * the worker to clone the repo itself. See RepoSource
     * for the capability gate and security expectations.
     *
     * Generated from protobuf field <code>.revund.worker.v1.RepoSource repo_source = 3;</code>
     * @param \Revund\Worker\V1\RepoSource $var
     * @return $this
     */
    public function setRepoSource(\Revund\Worker\V1\RepoSource|null $var)
    {
        $this->repo_source = $var;

        return $this;
    }

}

