<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * RepoSource tells a self-fetching worker how to obtain
 * the repo without depending on a shared filesystem with
 * the bot. The worker shallow-clones via git using these
 * values, caches the clone for the review's other RPCs,
 * and evicts on idle.
 * Capability gate: workers MUST advertise "self_fetch"
 * in Describe.Capabilities before the bot will send
 * `repo_source`. Workers without that capability ignore
 * the field entirely and use `repo_path`.
 * # Security expectations on workers
 *   - Use auth_token ONLY at clone time (as the password
 *     in https://x-access-token:<TOKEN>\@host/path.git).
 *   - Immediately after a successful clone, strip the
 *     token from the remote URL stored in .git/config.
 *   - Never log the token. Sanitize error messages that
 *     might include the URL.
 *   - Never persist the token to disk in any form.
 * Tokens are short-lived (typically 1 hour for GitHub
 * installation tokens) and scoped to the source repo's
 * permissions, so blast radius is bounded — but the
 * hygiene rules above still apply.
 *
 * Generated from protobuf message <code>revund.worker.v1.RepoSource</code>
 */
class RepoSource extends \Google\Protobuf\Internal\Message
{
    /**
     * url is the https clone URL, e.g.
     * "https://github.com/owner/repo.git" — no userinfo.
     * SSH URLs are not supported here — the bot's auth
     * model is bearer-token-over-https.
     *
     * Generated from protobuf field <code>string url = 1;</code>
     */
    protected $url = '';
    /**
     * ref is the commit SHA (preferred) or branch / tag
     * name to check out. Commit SHA is deterministic and
     * matches what GitHub / GitLab webhooks already give
     * us; branch/tag names are accepted for the local-dev
     * case but workers should warn when they receive one
     * (drift risk).
     *
     * Generated from protobuf field <code>string ref = 2;</code>
     */
    protected $ref = '';
    /**
     * auth_token is the bearer credential the worker uses
     * as the password in the clone URL. Typically a
     * platform installation access token (1h TTL).
     *
     * Generated from protobuf field <code>string auth_token = 3;</code>
     */
    protected $auth_token = '';
    /**
     * auth_user is the basic-auth username the worker
     * pairs with auth_token to compose the clone URL:
     *   https://<auth_user>:<auth_token>\@<host>/<path>
     * Defaults to "x-access-token" when empty — that's
     * GitHub's convention and works for the majority of
     * first-party deployments. Other platforms set this
     * explicitly:
     *   GitHub     → "x-access-token" (or empty)
     *   GitLab     → "oauth2"
     *   Bitbucket  → "x-token-auth"
     * Adding a new platform = the bot sets a new
     * auth_user string; workers don't need to know which
     * platform they're talking to.
     *
     * Generated from protobuf field <code>string auth_user = 4;</code>
     */
    protected $auth_user = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $url
     *           url is the https clone URL, e.g.
     *           "https://github.com/owner/repo.git" — no userinfo.
     *           SSH URLs are not supported here — the bot's auth
     *           model is bearer-token-over-https.
     *     @type string $ref
     *           ref is the commit SHA (preferred) or branch / tag
     *           name to check out. Commit SHA is deterministic and
     *           matches what GitHub / GitLab webhooks already give
     *           us; branch/tag names are accepted for the local-dev
     *           case but workers should warn when they receive one
     *           (drift risk).
     *     @type string $auth_token
     *           auth_token is the bearer credential the worker uses
     *           as the password in the clone URL. Typically a
     *           platform installation access token (1h TTL).
     *     @type string $auth_user
     *           auth_user is the basic-auth username the worker
     *           pairs with auth_token to compose the clone URL:
     *             https://<auth_user>:<auth_token>\@<host>/<path>
     *           Defaults to "x-access-token" when empty — that's
     *           GitHub's convention and works for the majority of
     *           first-party deployments. Other platforms set this
     *           explicitly:
     *             GitHub     → "x-access-token" (or empty)
     *             GitLab     → "oauth2"
     *             Bitbucket  → "x-token-auth"
     *           Adding a new platform = the bot sets a new
     *           auth_user string; workers don't need to know which
     *           platform they're talking to.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * url is the https clone URL, e.g.
     * "https://github.com/owner/repo.git" — no userinfo.
     * SSH URLs are not supported here — the bot's auth
     * model is bearer-token-over-https.
     *
     * Generated from protobuf field <code>string url = 1;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * url is the https clone URL, e.g.
     * "https://github.com/owner/repo.git" — no userinfo.
     * SSH URLs are not supported here — the bot's auth
     * model is bearer-token-over-https.
     *
     * Generated from protobuf field <code>string url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->url = $var;

        return $this;
    }

    /**
     * ref is the commit SHA (preferred) or branch / tag
     * name to check out. Commit SHA is deterministic and
     * matches what GitHub / GitLab webhooks already give
     * us; branch/tag names are accepted for the local-dev
     * case but workers should warn when they receive one
     * (drift risk).
     *
     * Generated from protobuf field <code>string ref = 2;</code>
     * @return string
     */
    public function getRef()
    {
        return $this->ref;
    }

    /**
     * ref is the commit SHA (preferred) or branch / tag
     * name to check out. Commit SHA is deterministic and
     * matches what GitHub / GitLab webhooks already give
     * us; branch/tag names are accepted for the local-dev
     * case but workers should warn when they receive one
     * (drift risk).
     *
     * Generated from protobuf field <code>string ref = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRef(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->ref = $var;

        return $this;
    }

    /**
     * auth_token is the bearer credential the worker uses
     * as the password in the clone URL. Typically a
     * platform installation access token (1h TTL).
     *
     * Generated from protobuf field <code>string auth_token = 3;</code>
     * @return string
     */
    public function getAuthToken()
    {
        return $this->auth_token;
    }

    /**
     * auth_token is the bearer credential the worker uses
     * as the password in the clone URL. Typically a
     * platform installation access token (1h TTL).
     *
     * Generated from protobuf field <code>string auth_token = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthToken(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->auth_token = $var;

        return $this;
    }

    /**
     * auth_user is the basic-auth username the worker
     * pairs with auth_token to compose the clone URL:
     *   https://<auth_user>:<auth_token>\@<host>/<path>
     * Defaults to "x-access-token" when empty — that's
     * GitHub's convention and works for the majority of
     * first-party deployments. Other platforms set this
     * explicitly:
     *   GitHub     → "x-access-token" (or empty)
     *   GitLab     → "oauth2"
     *   Bitbucket  → "x-token-auth"
     * Adding a new platform = the bot sets a new
     * auth_user string; workers don't need to know which
     * platform they're talking to.
     *
     * Generated from protobuf field <code>string auth_user = 4;</code>
     * @return string
     */
    public function getAuthUser()
    {
        return $this->auth_user;
    }

    /**
     * auth_user is the basic-auth username the worker
     * pairs with auth_token to compose the clone URL:
     *   https://<auth_user>:<auth_token>\@<host>/<path>
     * Defaults to "x-access-token" when empty — that's
     * GitHub's convention and works for the majority of
     * first-party deployments. Other platforms set this
     * explicitly:
     *   GitHub     → "x-access-token" (or empty)
     *   GitLab     → "oauth2"
     *   Bitbucket  → "x-token-auth"
     * Adding a new platform = the bot sets a new
     * auth_user string; workers don't need to know which
     * platform they're talking to.
     *
     * Generated from protobuf field <code>string auth_user = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthUser(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->auth_user = $var;

        return $this;
    }

}

