<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>revund.worker.v1.ResolveResponse</code>
 */
class ResolveResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.SymbolDecl symbols = 1;</code>
     */
    private $symbols;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Revund\Worker\V1\SymbolDecl[] $symbols
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.SymbolDecl symbols = 1;</code>
     * @return RepeatedField<\Revund\Worker\V1\SymbolDecl>
     */
    public function getSymbols()
    {
        return $this->symbols;
    }

    /**
     * Generated from protobuf field <code>repeated .revund.worker.v1.SymbolDecl symbols = 1;</code>
     * @param \Revund\Worker\V1\SymbolDecl[] $var
     * @return $this
     */
    public function setSymbols(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Revund\Worker\V1\SymbolDecl::class);
        $this->symbols = $arr;

        return $this;
    }

}

