<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>revund.worker.v1.ResolveRequest</code>
 */
class ResolveRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Absolute repo root path. See ParseRequest.repo_path
     * for the repo_path / repo_source contract.
     *
     * Generated from protobuf field <code>string repo_path = 1;</code>
     */
    protected $repo_path = '';
    /**
     * The unified diff being reviewed. The worker extracts
     * referenced-but-undeclared identifiers from the diff
     * and looks up their declarations.
     *
     * Generated from protobuf field <code>string diff = 2;</code>
     */
    protected $diff = '';
    /**
     * Repo-relative paths of changed files. Authoritative
     * when present; the worker may also derive its own list
     * from the diff.
     *
     * Generated from protobuf field <code>repeated string changed_files = 3;</code>
     */
    private $changed_files;
    /**
     * Self-fetch source — set when the worker should clone
     * the repo itself instead of reading from repo_path.
     *
     * Generated from protobuf field <code>.revund.worker.v1.RepoSource repo_source = 4;</code>
     */
    protected $repo_source = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $repo_path
     *           Absolute repo root path. See ParseRequest.repo_path
     *           for the repo_path / repo_source contract.
     *     @type string $diff
     *           The unified diff being reviewed. The worker extracts
     *           referenced-but-undeclared identifiers from the diff
     *           and looks up their declarations.
     *     @type string[] $changed_files
     *           Repo-relative paths of changed files. Authoritative
     *           when present; the worker may also derive its own list
     *           from the diff.
     *     @type \Revund\Worker\V1\RepoSource $repo_source
     *           Self-fetch source — set when the worker should clone
     *           the repo itself instead of reading from repo_path.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * Absolute repo root path. See ParseRequest.repo_path
     * for the repo_path / repo_source contract.
     *
     * Generated from protobuf field <code>string repo_path = 1;</code>
     * @return string
     */
    public function getRepoPath()
    {
        return $this->repo_path;
    }

    /**
     * Absolute repo root path. See ParseRequest.repo_path
     * for the repo_path / repo_source contract.
     *
     * Generated from protobuf field <code>string repo_path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRepoPath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->repo_path = $var;

        return $this;
    }

    /**
     * The unified diff being reviewed. The worker extracts
     * referenced-but-undeclared identifiers from the diff
     * and looks up their declarations.
     *
     * Generated from protobuf field <code>string diff = 2;</code>
     * @return string
     */
    public function getDiff()
    {
        return $this->diff;
    }

    /**
     * The unified diff being reviewed. The worker extracts
     * referenced-but-undeclared identifiers from the diff
     * and looks up their declarations.
     *
     * Generated from protobuf field <code>string diff = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDiff(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->diff = $var;

        return $this;
    }

    /**
     * Repo-relative paths of changed files. Authoritative
     * when present; the worker may also derive its own list
     * from the diff.
     *
     * Generated from protobuf field <code>repeated string changed_files = 3;</code>
     * @return RepeatedField<string>
     */
    public function getChangedFiles()
    {
        return $this->changed_files;
    }

    /**
     * Repo-relative paths of changed files. Authoritative
     * when present; the worker may also derive its own list
     * from the diff.
     *
     * Generated from protobuf field <code>repeated string changed_files = 3;</code>
     * @param string[] $var
     * @return $this
     */
    public function setChangedFiles(array|RepeatedField $var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->changed_files = $arr;

        return $this;
    }

    /**
     * Self-fetch source — set when the worker should clone
     * the repo itself instead of reading from repo_path.
     *
     * Generated from protobuf field <code>.revund.worker.v1.RepoSource repo_source = 4;</code>
     * @return \Revund\Worker\V1\RepoSource|null
     */
    public function getRepoSource()
    {
        return $this->repo_source;
    }

    public function hasRepoSource()
    {
        return isset($this->repo_source);
    }

    public function clearRepoSource()
    {
        unset($this->repo_source);
    }

    /**
     * Self-fetch source — set when the worker should clone
     * the repo itself instead of reading from repo_path.
     *
     * Generated from protobuf field <code>.revund.worker.v1.RepoSource repo_source = 4;</code>
     * @param \Revund\Worker\V1\RepoSource $var
     * @return $this
     */
    public function setRepoSource(\Revund\Worker\V1\RepoSource|null $var)
    {
        $this->repo_source = $var;

        return $this;
    }

}

