<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto

namespace Revund\Worker\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>revund.worker.v1.SymbolDecl</code>
 */
class SymbolDecl extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * repo-relative
     *
     * Generated from protobuf field <code>string file_path = 2;</code>
     */
    protected $file_path = '';
    /**
     * Generated from protobuf field <code>int32 start_line = 3;</code>
     */
    protected $start_line = 0;
    /**
     * Generated from protobuf field <code>int32 end_line = 4;</code>
     */
    protected $end_line = 0;
    /**
     * full declaration source
     *
     * Generated from protobuf field <code>string text = 5;</code>
     */
    protected $text = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $file_path
     *           repo-relative
     *     @type int $start_line
     *     @type int $end_line
     *     @type string $text
     *           full declaration source
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Worker::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * repo-relative
     *
     * Generated from protobuf field <code>string file_path = 2;</code>
     * @return string
     */
    public function getFilePath()
    {
        return $this->file_path;
    }

    /**
     * repo-relative
     *
     * Generated from protobuf field <code>string file_path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFilePath(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->file_path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 start_line = 3;</code>
     * @return int
     */
    public function getStartLine()
    {
        return $this->start_line;
    }

    /**
     * Generated from protobuf field <code>int32 start_line = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setStartLine(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->start_line = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 end_line = 4;</code>
     * @return int
     */
    public function getEndLine()
    {
        return $this->end_line;
    }

    /**
     * Generated from protobuf field <code>int32 end_line = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setEndLine(int $var)
    {
        GPBUtil::checkInt32($var);
        $this->end_line = $var;

        return $this;
    }

    /**
     * full declaration source
     *
     * Generated from protobuf field <code>string text = 5;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * full declaration source
     *
     * Generated from protobuf field <code>string text = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setText(string $var)
    {
        GPBUtil::checkString($var, true);
        $this->text = $var;

        return $this;
    }

}

